/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

/*
 *  This is the result of class-dump -r -C '(AppleScript)|(AppleEvent)' called on all 
 *  frameworks in /System/Library/Frameworks/ and /System/Library/PrivateFrameworks/
 *
 *  The stuff from the Message framework looks kind of interesting.
 */

/*
 * File: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@interface NSAppleEventDescriptor : NSObject <NSCopying>
{
    struct AEDesc _desc;
    BOOL _hasValidDesc;
    char _padding[3];
}

+ (id)nullDescriptor;
+ (id)descriptorWithDescriptorType:(unsigned long)fp8 bytes:(const void *)fp12 length:(unsigned int)fp16;
+ (id)descriptorWithDescriptorType:(unsigned long)fp8 data:(id)fp12;
+ (id)descriptorWithBoolean:(unsigned char)fp8;
+ (id)descriptorWithEnumCode:(unsigned long)fp8;
+ (id)descriptorWithInt32:(long)fp8;
+ (id)descriptorWithTypeCode:(unsigned long)fp8;
+ (id)descriptorWithString:(id)fp8;
+ (id)appleEventWithEventClass:(unsigned long)fp8 eventID:(unsigned long)fp12 targetDescriptor:(id)fp16 returnID:(short)fp20 transactionID:(long)fp24;
+ (id)listDescriptor;
+ (id)recordDescriptor;
- (id)init;
- (id)initWithAEDescNoCopy:(const struct AEDesc *)fp8;
- (id)initWithDescriptorType:(unsigned long)fp8 bytes:(const void *)fp12 length:(unsigned int)fp16;
- (id)initWithDescriptorType:(unsigned long)fp8 data:(id)fp12;
- (id)initWithEventClass:(unsigned long)fp8 eventID:(unsigned long)fp12 targetDescriptor:(id)fp16 returnID:(short)fp20 transactionID:(long)fp24;
- (id)initListDescriptor;
- (id)initRecordDescriptor;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (const struct AEDesc *)aeDesc;
- (unsigned long)descriptorType;
- (id)data;
- (unsigned char)booleanValue;
- (unsigned long)enumCodeValue;
- (long)int32Value;
- (unsigned long)typeCodeValue;
- (id)stringValue;
- (unsigned long)eventClass;
- (unsigned long)eventID;
- (short)returnID;
- (long)transactionID;
- (void)setParamDescriptor:(id)fp8 forKeyword:(unsigned long)fp12;
- (id)paramDescriptorForKeyword:(unsigned long)fp8;
- (void)removeParamDescriptorWithKeyword:(unsigned long)fp8;
- (void)setAttributeDescriptor:(id)fp8 forKeyword:(unsigned long)fp12;
- (id)attributeDescriptorForKeyword:(unsigned long)fp8;
- (int)numberOfItems;
- (void)insertDescriptor:(id)fp8 atIndex:(long)fp12;
- (id)descriptorAtIndex:(long)fp8;
- (void)removeDescriptorAtIndex:(long)fp8;
- (void)setDescriptor:(id)fp8 forKeyword:(unsigned long)fp12;
- (id)descriptorForKeyword:(unsigned long)fp8;
- (void)removeDescriptorWithKeyword:(unsigned long)fp8;
- (unsigned long)keywordForDescriptorAtIndex:(long)fp8;
- (id)coerceToDescriptorType:(unsigned long)fp8;

@end

@interface NSAppleEventDescriptor (NSTemporaryCompatibility)
- (id)_initWithDescriptorType:(unsigned long)fp8 bytes:(const void *)fp12 byteCount:(unsigned long)fp16;
- (id)_initWithoutAEDesc;
- (struct AEDesc *)_AEDesc;
- (void)_setAEDesc:(struct AEDesc *)fp8;
@end

@interface NSAppleEventDescriptor (NSCompatibility)
- (void)removeDecriptorAtIndex:(long)fp8;
@end

@interface NSAppleEventDescriptor (NSPrivate)
+ (id)_descriptorWithNumber:(id)fp8;
- (void)_copyValueOfDescriptorType:(unsigned long)fp8 toBuffer:(void *)fp12 ofLength:(unsigned long)fp16;
- (id)_fileURLValue;
- (id)_fsRefValue;
- (id)_singleFilePathValue;
- (id)_filePathValue;
- (void)_flushAEDesc;
@end

@interface NSAppleEventManager : NSObject
{
    BOOL _isPreparedForDispatch;
    char _padding[3];
}

+ (id)sharedAppleEventManager;
- (id)init;
- (void)setEventHandler:(id)fp8 andSelector:(SEL)fp12 forEventClass:(unsigned long)fp16 andEventID:(unsigned long)fp20;
- (void)removeEventHandlerForEventClass:(unsigned long)fp8 andEventID:(unsigned long)fp12;
- (void)_pushHandling:(id)fp8;
- (id)_poppedTopHandling;
- (short)dispatchRawAppleEvent:(const struct AEDesc *)fp8 withRawReply:(struct AEDesc *)fp12 handlerRefCon:(unsigned long)fp16;
- (id)currentAppleEvent;
- (id)currentReplyAppleEvent;
- (struct __NSAppleEventManagerSuspension *)suspendCurrentAppleEvent;
- (id)appleEventForSuspensionID:(struct __NSAppleEventManagerSuspension *)fp8;
- (id)replyAppleEventForSuspensionID:(struct __NSAppleEventManagerSuspension *)fp8;
- (void)setCurrentAppleEventAndReplyEventWithSuspensionID:(struct __NSAppleEventManagerSuspension *)fp8;
- (void)resumeWithSuspensionID:(struct __NSAppleEventManagerSuspension *)fp8;

@end

@interface NSAppleEventHandling : NSObject
{
    NSAppleEventDescriptor *_event;
    NSAppleEventDescriptor *_replyEvent;
    NSScriptCommand *_scriptCommand;
    BOOL _isSuspended;
    BOOL _isSuspendedWithAE;
    char _padding[2];
}

- (id)initWithEvent:(const struct AEDesc *)fp8 replyEvent:(struct AEDesc *)fp12;
- (void)dealloc;
- (void)setScriptCommand:(id)fp8;
- (id)event;
- (id)replyEvent;
- (id)scriptCommand;
- (id)suspend;
- (BOOL)isSuspended;
- (void)resumeWithScriptCommandResult:(id)fp8;

@end

@interface NSAppleEventManager (NSTemporaryCompatibility)
- (void)_prepareToDispatch;
@end

@interface NSAppleEventManager (NSInternal)
- (void)_sendDidFailToDispatchNotification;
- (void)_removeHandlingIfPresent:(id)fp8;
- (id)_topHandling;
@end

@interface NSAppleEventManager (NSPrivate)
- (void)_prepareForDispatch;
@end

@interface NSAppleScript : NSObject <NSCopying>
{
    NSString *_source;
    unsigned long _compiledScriptID;
    void *_reserved1;
    void *_reserved2;
}

+ (id)_infoForOSAError:(long)fp8;
- (id)_initWithScriptIDNoCopy:(unsigned long)fp8;
- (id)_initWithData:(id)fp8 error:(id *)fp12;
- (id)_initWithContentsOfFile:(id)fp8 error:(id *)fp12;
- (id)initWithContentsOfURL:(id)fp8 error:(id *)fp12;
- (id)initWithSource:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)source;
- (BOOL)isCompiled;
- (BOOL)compileAndReturnError:(id *)fp8;
- (id)executeAndReturnError:(id *)fp8;
- (id)executeAppleEvent:(id)fp8 error:(id *)fp12;

@end

@interface NSAppleScript (NSPrivate)
+ (struct ComponentInstanceRecord *)_defaultScriptingComponent;
- (unsigned long)_compiledScriptID;
@end

@interface NSScriptingAppleEventHandler : NSObject
{
}

+ (id)sharedScriptingAppleEventHandler;
- (void)registerForCommandDescription:(id)fp8;
- (void)handleCommandEvent:(id)fp8 withReplyEvent:(id)fp12;
- (void)handleGetAETEEvent:(id)fp8 withReplyEvent:(id)fp12;

@end

/*
 * File: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 */

@interface NSAppleScript (NSExtensions)
+ (id)_attributedStringFromDescriptor:(id)fp8;
- (id)richTextSource;
@end

@interface NSApplication (NSAppleEventHandling)
- (void)_handleAEOpen;
- (void)_handleAEReopen;
- (short)_handleAEOpenDocuments:(id)fp8;
- (short)_handleAEPrintDocuments:(id)fp8;
- (short)_handleAEQuitWithActivating:(BOOL)fp8 documentSaving:(int)fp12;
- (void)_handleCoreEvent:(id)fp8 withReplyEvent:(id)fp12;
- (void)_registerRequiredAEHandlers;
@end


/*
 * File: /System/Library/Frameworks/AppleScriptKit.framework/Versions/A/AppleScriptKit
 */

@interface NSObject (AppleScriptKit)
- (id)eventHandlers;
- (void)setEventHandlers:(id)fp8;
- (unsigned int)objectIndex;
- (id)objectName;
- (void)setObjectName:(id)fp8;
- (int)objectID;
- (void)setObjectID:(int)fp8;
- (id)objectScript;
- (void)setObjectScript:(id)fp8;
- (id)scriptController;
- (void)setScriptController:(id)fp8;
- (void)removeFromMaps;
- (id)objectSpecifier;
- (void)addEventHandler:(id)fp8;
- (void)addEventHandler:(id)fp8 enable:(BOOL)fp12;
- (void)enableEventHandler:(id)fp8;
- (void)removeEventHandler:(id)fp8;
- (void)addAndEnableKindOfEventHandler:(id)fp8;
- (BOOL)eventHandlerIsSupported:(id)fp8;
- (BOOL)hasKindOfEventHandler:(id)fp8;
@end


/*
 * File: /System/Library/Frameworks/Message.framework/Versions/B/Message
 */

@interface SpecialMailboxUid (AppleScript)
+ (id)appleScriptNameForMailboxType:(int)fp8;
- (id)appleScriptKey;
- (id)objectSpecifier;
- (id)messages;
@end

@interface NSAppleEventDescriptor (MailAdditions)
- (long)sendNoReplyWithMode:(long)fp8 priority:(short)fp12;
- (long)sendNoReply;
@end

@interface NSArray (AppleScriptConveniences)
- (id)arrayByEvaluatingObjectSpecifiers;
@end

@interface NSAppleScript (MessageRuleAdditions)
+ (id)_createScriptAtPath:(id)fp8 errorInfo:(id *)fp12;
+ (BOOL)executeHandlerWithName:(id)fp8 inScriptAtPath:(id)fp12 withArguments:(id)fp16 error:(id *)fp20;
+ (BOOL)executeHandlerWithEventClass:(unsigned long)fp8 eventID:(unsigned long)fp12 inScriptAtPath:(id)fp16 withArguments:(id)fp20 error:(id *)fp24;
- (id)executeHandlerWithName:(id)fp8 andArguments:(id)fp12 error:(id *)fp16;
- (id)executeHandlerWithEventClass:(unsigned long)fp8 eventID:(unsigned long)fp12 andArguments:(id)fp16 error:(id *)fp20;
- (BOOL)compileAndReturnError:(id *)fp8;
@end

@interface AppleScriptHeaderRecord : NSObject
{
    NSString *_name;
    id _content;
    Message *_message;
}

- (void)dealloc;
- (id)name;
- (void)setName:(id)fp8;
- (id)content;
- (void)setContent:(id)fp8;
- (id)message;
- (void)setMessage:(id)fp8;
- (id)objectSpecifier;

@end


/*
 * File: /System/Library/PrivateFrameworks/DevToolsInterface.framework/Versions/A/DevToolsInterface
 */

@interface PBXAppleScriptBuildPhaseModule : PBXFileBuildPhaseModule
{
    NSPopUpButton *_contextPopup;
    NSTextField *_contextNameField;
}

- (id)initWithBuildPhase:(id)fp8;
- (void)viewDidLoad;
- (void)update;
- (void)controlTextDidChange:(id)fp8;
- (void)takeContextFrom:(id)fp8;
- (void)takeContextNameFrom:(id)fp8;

@end

@interface PBXAppleScriptBuildPhaseInspectorPane : PBXInspectorPaneModule
{
    NSTextField *_contextNameField;
    NSPopUpButton *_contextPopup;
}

+ (BOOL)canInspectItems:(id)fp8;
+ (id)inspectableClasses;
+ (id)alternateLabel;
- (void)_setContextName;
- (void)_setIsSharedContext;
- (void)currentInspectedItemsChanged:(id)fp8;
- (void)takeContextFrom:(id)fp8;
- (void)takeContextNameFrom:(id)fp8;

@end


/*
 * File: /System/Library/PrivateFrameworks/DevToolsCore.framework/Versions/A/DevToolsCore
 */

@interface NSAppleEventDescriptor (PBXFoundationExtensions)
+ (id)fileDescriptorFromPath:(id)fp8;
+ (id)documentDescriptorFromFilename:(id)fp8;
- (id)hierarchicalDescription;
- (id)descriptionAtIndentLevel:(int)fp8;
- (int)send;
- (id)sendAppleEventAndWaitForReply;
@end

@interface PBXAppleScriptBuildPhase : PBXBuildPhase
{
    BOOL _isSharedContext;
    NSString *_contextName;
}

+ (id)identifier;
+ (id)defaultName;
+ (id)jamName;
+ (id)allowedExtensions;
+ (id)archivableAttributes;
- (id)initWithName:(id)fp8;
- (id)init;
- (void)dealloc;
- (BOOL)isSharedContext;
- (void)setIsSharedContext:(BOOL)fp8;
- (BOOL)isDefaultContext;
- (void)setIsDefaultContext:(BOOL)fp8;
- (id)contextName;
- (void)setContextName:(id)fp8;
- (void)setDefaultAttributesForNewBuildFile:(id)fp8;
- (void)writeToJamString:(id)fp8;

@end


/*
 * File: /System/Library/PrivateFrameworks/InternetConnect.framework/Versions/A/InternetConnect
 */

@interface InternetConnectPlugIn (AppleScriptAirPortSupport)
- (id)networkName;
@end

@interface InternetConnectPlugIn (AppleScriptPPPSupport)
- (id)phoneNumber;
- (id)userName;
@end

@interface InternetConnectPlugIn (AppleScriptSupport)
- (void)connect;
- (void)connectWithUserName:(id)fp8 password:(id)fp12 address:(id)fp16;
- (void)disconnect;
- (id)dialer;
@end

@interface InternetConnectPPPDialer (AppleScriptSupport)
- (id)userName;
- (id)serverName;
- (id)message;
- (long)bytesIn;
- (long)bytesOut;
@end

